# yaml-language-server: $schema=../../schema.json
name: php
image: tanjun/php
build:
    remote_build: true
    build_pack:
        type: php
server:
    address: 127.0.0.1
proxy:
    host: localhost
    healthcheck:
        path: /
