# yaml-language-server: $schema=../../schema.json
name: bun
image: ghcr.io/shyim/bun
build:
    remote_build: true
server:
    address: 127.0.0.1
proxy:
    host: localhost
    healthcheck:
        path: /
