# yaml-language-server: $schema=../../schema.json
name: go
image: tanjun/go
build:
    remote_build: true
    build_pack:
        type: go
        settings:

server:
    address: 127.0.0.1
proxy:
    host: localhost
    healthcheck:
        path: /
