# yaml-language-server: $schema=../../schema.json
name: node
image: tanjun/node
build:
    remote_build: true
    build_pack:
        type: node
server:
    address: 127.0.0.1
proxy:
    host: localhost
    healthcheck:
        path: /
