# yaml-language-server: $schema=../../schema.json
server:
  address: 127.0.0.1
name: shopware
image: tanjun/shopware
build:
  remote_build: true
  build_pack:
    type: shopware
proxy:
  host: localhost
  healthcheck:
    path: /admin
app:
  env:
    APP_URL:
      expr: '"http://" + config.Proxy.Host'
    TRUSTED_PROXIES:
      value: REMOTE_ADDR
    DATABASE_URL:
      expr: 'service.database.url'
  initial_secrets:
    APP_SECRET:
      expr: 'randomString(32)'
  mounts:
    jwt:
      path: config/jwt
    files:
      path: files
    bundles:
      path: public/bundles
    theme:
      path: public/theme
    media:
      path: public/media
    thumbnail:
      path: public/thumbnail
    sitemap:
      path: public/sitemap
  workers:
    worker:
      command: 'php bin/console messenger:consume async --time-limit=3600'
  cronjobs:
    - name: scheduled-task
      schedule: '@every 5m'
      command: 'php bin/console scheduled-task:run --no-wait'
  hooks:
    deploy: |
      ./vendor/bin/shopware-deployment-helper run --skip-theme-compile
    post_deploy: |
      ./bin/console theme:compile --active-only

services:
  database:
    type: mysql:8.0
    settings:
      sql_mode: 'error_for_division_by_zero'
  cache:
    type: valkey:8.0
