name: Golang CI Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '*.go'
      - '**/*.go'
  pull_request:
    paths:
      - '*.go'
      - '**/*.go'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 4m
