name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
          check-latest: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.17.2

      - uses: octo-sts/action@v1.0.0
        id: sts-homebrew
        with:
          scope: shyim/homebrew-tap
          identity: release

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ steps.sts-homebrew.outputs.token }}

      - name: Install Cloudsmith CLI
        run: pip install --upgrade cloudsmith-cli

      - name: Cloudsmith Uploads
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          for filename in dist/*.deb; do
              cloudsmith push deb tanjun/stable/any-distro/any-version $filename
          done
          for filename in dist/*.rpm; do
              cloudsmith push rpm tanjun/stable/any-distro/any-version $filename
          done
          for filename in dist/*.apk; do
              cloudsmith push alpine tanjun/stable/alpine/any-version $filename
          done
